name: 'clairvoyance'
version: '1.0.0'
config-version: 2

profile: 'clairvoyance'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  clairvoyance:
    dwd:
      +materialized: table
      +dataset: dwd
    dws:
      +materialized: table
      +dataset: dws
    ads:
      +materialized: table
      +dataset: ads
